<?php

return [

    'hope-kitchen' => [
        'slug' => 'hope-kitchen',
        'name' => 'Hope Kitchen',
        'tag' => 'Food Security',
        'meta_description' => 'Hope Kitchen — CHJ Foundation\'s food security program in Abuja. Over 148,000 meals served to families facing hunger since 2018.',
        'hero_intro' => 'The original program of CHJ Foundation. Every Saturday morning since 2018, a pot of rice has been on the stove in Wuse 2 — and a line of children waiting with bowls.',
        'hero_image' => 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'quick_stats' => [
            ['value' => '148K+', 'label' => 'Meals served'],
            ['value' => '600', 'label' => 'Families fed weekly'],
            ['value' => '3', 'label' => 'Locations'],
        ],
        'about_title' => 'No one in our community should go to bed hungry.',
        'about_paragraphs' => [
            'Hunger is not abstract in the settlements we serve. It is a mother dividing one portion of rice into four bowls so her children do not notice. It is a grandfather skipping dinner so his granddaughter can eat. It is a child falling asleep in school because there was no breakfast.',
            'Hope Kitchen began in 2018 with a single Saturday meal in Jabi settlement. The first week, 40 children came. By the end of the year, 200 were lining up with plastic bowls. Today, we run three weekly community meal sites, distribute dry rations to over 600 families every two weeks, and respond to emergency food crises within 48 hours.',
            'But Hope Kitchen is more than food. It is presence. It is consistency. It is a place where families know they will be welcomed by name, asked about their children, prayed for if they wish, and sent home with dignity — not pity.',
            'We buy rice, beans, oil, and seasoning in bulk from local markets. We employ three full-time cooks and rotate 40 volunteers through weekly shifts. Every meal costs us about ₦220 per person — roughly the price of a bottle of soda.',
        ],
        'approach_points' => [
            ['title' => 'Weekly community meals', 'desc' => 'Three sites: Jabi, Nyanya, and Gwarinpa. Every Saturday, 12pm. Open to all, no questions asked.'],
            ['title' => 'Biweekly dry ration parcels', 'desc' => 'Enough rice, beans, oil, and seasoning to feed a family of five for two weeks. Distributed to 600+ registered families.'],
            ['title' => 'Emergency food response', 'desc' => 'When a family is displaced by fire, flood, or eviction, we deliver food within 48 hours — coordinated through our network of community leaders.'],
            ['title' => 'School feeding partnership', 'desc' => 'We provide lunch daily for 240 children in two community primary schools, in partnership with local government.'],
        ],
        'quote' => [
            'text' => 'When my husband passed, I had no idea how to feed my four children. Hope Kitchen didn\'t just give us food — they gave me back my dignity. Today I work in their kitchen, serving other mothers.',
            'author' => 'Amina, mother of four, Gwarinpa',
        ],
        'gallery' => [
            ['src' => 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Volunteers preparing meals'],
            ['src' => 'https://images.unsplash.com/photo-1593113598332-cd288d649433?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Children receiving meals'],
            ['src' => 'https://images.unsplash.com/photo-1607582544185-66fdfaee69ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Dry ration distribution'],
            ['src' => 'https://images.unsplash.com/photo-1574484184081-afea8a62f9b6?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Family receiving food parcel'],
        ],
        'sidebar_facts' => [
            ['label' => 'Started', 'value' => '2018'],
            ['label' => 'Locations', 'value' => '3 sites in FCT'],
            ['label' => 'Meals served (2024)', 'value' => '148,400'],
            ['label' => 'Families on ration list', 'value' => '612'],
            ['label' => 'Cost per meal', 'value' => '₦220'],
            ['label' => 'Full-time staff', 'value' => '3'],
        ],
        'support_text' => '₦5,000 feeds a family of five for one week. ₦25,000 sponsors a family for a month. Every gift is stewarded carefully — we publish full audited accounts annually.',
    ],

    'safe-harbor' => [
        'slug' => 'safe-harbor',
        'name' => 'Safe Harbor',
        'tag' => 'Anti-Trafficking',
        'meta_description' => 'Safe Harbor — CHJ Foundation\'s anti-trafficking program. Rescue, recovery, and reintegration for survivors of human trafficking in Nigeria.',
        'hero_intro' => 'A 24/7 rescue line. A safe house with capacity for 20 survivors. Trauma-informed care, legal advocacy, and a path home — in partnership with NAPTIP.',
        'hero_image' => 'https://images.unsplash.com/photo-1521791136064-7986c2920216?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'quick_stats' => [
            ['value' => '320', 'label' => 'Survivors supported'],
            ['value' => '20', 'label' => 'Safe house capacity'],
            ['value' => '24/7', 'label' => 'Rescue line'],
        ],
        'about_title' => 'Human trafficking is not far away. It happens in our neighborhoods.',
        'about_paragraphs' => [
            'Nigeria is a source, transit, and destination country for human trafficking. The National Agency for the Prohibition of Trafficking in Persons (NAPTIP) receives thousands of reports each year — and those are only the ones that get reported. The real numbers are far higher.',
            'Safe Harbor was launched in 2019, a year after CHJ Foundation was formally registered, when we encountered our first case: a 14-year-old girl from Benue State who had been brought to Abuja with promises of education, then forced into domestic servitude. We helped her return home — and realized we needed to do this at scale.',
            'Today, Safe Harbor operates a 24/7 rescue line, a safe house in a confidential Abuja location with capacity for 20 survivors, a team of trauma-informed counselors, social workers, and legal advocates. We work in formal partnership with NAPTIP, the Nigeria Police Force, and international anti-trafficking organizations.',
            'Our approach is survivor-centered at every stage. We do not rescue people into a program — we walk with them through every step of recovery, for as long as they need us. Some survivors stay three months. Some have been with us for three years. All are family.',
        ],
        'approach_points' => [
            ['title' => '24/7 rescue line', 'desc' => 'A confidential hotline staffed by trained responders. We coordinate with NAPTIP and local police for safe extraction within 12 hours of a confirmed case.'],
            ['title' => 'Confidential safe house', 'desc' => 'A 20-bed facility in an undisclosed Abuja location, staffed 24/7. Counseling, medical care, education, and life skills — for as long as recovery takes.'],
            ['title' => 'Trauma-informed counseling', 'desc' => 'Individual and group therapy with licensed counselors, plus faith-based spiritual care for those who request it.'],
            ['title' => 'Family reunification', 'desc' => 'Where safe and possible, we work to reunite survivors with family — including family preparation, economic empowerment, and follow-up visits.'],
            ['title' => 'Vocational training & legal advocacy', 'desc' => 'Through our Pathways program, survivors gain skills and employment. Our legal team advocates for prosecution of traffickers and supports survivors through court proceedings.'],
        ],
        'quote' => [
            'text' => 'I was 16 when Safe Harbor found me. I had given up hope of ever seeing my family again. Today I am in university studying social work — because someone believed I was worth rescuing.',
            'author' => 'Grace, Safe Harbor graduate, now in university',
        ],
        'gallery' => [
            ['src' => 'https://images.unsplash.com/photo-1521791136064-7986c2920216?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Counseling session'],
            ['src' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Survivor support worker'],
            ['src' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Skills training'],
            ['src' => 'https://images.unsplash.com/photo-1577896851231-70ef18881754?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Safe space'],
        ],
        'sidebar_facts' => [
            ['label' => 'Started', 'value' => '2019'],
            ['label' => 'Survivors supported', 'value' => '320'],
            ['label' => 'Safe house capacity', 'value' => '20 beds'],
            ['label' => 'Average length of stay', 'value' => '8 months'],
            ['label' => 'Reunification rate', 'value' => '64%'],
            ['label' => 'Partner agencies', 'value' => 'NAPTIP, NPF, IOM'],
        ],
        'support_text' => 'Safe Harbor is one of our most expensive programs to run — and one of the most important. ₦150,000 sponsors one survivor\'s recovery for a month. Will you stand with us?',
    ],

    'pathways' => [
        'slug' => 'pathways',
        'name' => 'Pathways',
        'tag' => 'Education & Jobs',
        'meta_description' => 'Pathways — CHJ Foundation\'s education and jobs program. Scholarships, vocational training, and job placement for young people in Abuja.',
        'hero_intro' => 'Scholarships, vocational training, and job placement for young people ready to build a future — including trafficking survivors reintegrating into society.',
        'hero_image' => 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'quick_stats' => [
            ['value' => '680', 'label' => 'Graduates employed'],
            ['value' => '200', 'label' => 'On scholarship'],
            ['value' => '6', 'label' => 'Trades taught'],
        ],
        'about_title' => 'Education is the surest path out of poverty. We make it possible.',
        'about_paragraphs' => [
            'In the communities we serve, the difference between a young person who makes it and one who does not often comes down to one thing: opportunity. A family that can afford school fees. A mentor who believes in them. A loan for a sewing machine.',
            'Pathways exists to close that gap. We provide full secondary school scholarships for 200 students from low-income families. We run vocational training programs in six trades, with cohorts of 24 students each. We place graduates into jobs through our network of corporate partners.',
            'Our vocational programs run for 6 months, followed by a 3-month internship. Trades include tailoring, catering, IT/computer services, hairdressing, plumbing, and solar installation — chosen based on local labor market demand. 87% of our graduates are employed within 6 months of completion.',
            'For survivors of trafficking graduating from Safe Harbor, Pathways is often the next chapter. We integrate them into our regular cohorts, with additional trauma-informed support, and we have seen them thrive alongside other students.',
        ],
        'approach_points' => [
            ['title' => 'Secondary school scholarships', 'desc' => 'Full coverage of fees, uniforms, books, and transportation for 200 students annually. Merit and need-based selection.'],
            ['title' => 'Vocational training', 'desc' => 'Six-month intensive programs in tailoring, catering, IT, hairdressing, plumbing, and solar installation. Cohorts of 24.'],
            ['title' => 'Internship & job placement', 'desc' => 'Three-month internship after training, plus active job placement support through corporate and small business partners.'],
            ['title' => 'Microenterprise startup kits', 'desc' => 'For graduates starting their own businesses: a starter kit (e.g., sewing machine, catering equipment) and a small grant.'],
            ['title' => 'Alumni network', 'desc' => 'Quarterly gatherings, ongoing mentorship, and a WhatsApp community of 400+ graduates supporting each other.'],
        ],
        'quote' => [
            'text' => 'I dropped out of school at 15 because my parents could not afford the fees. Today, after Pathways, I run my own tailoring shop with two apprentices. I employ people. I pay taxes. I never thought this was possible for someone like me.',
            'author' => 'Tunde, Pathways graduate, Class of 2023',
        ],
        'gallery' => [
            ['src' => 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Classroom session'],
            ['src' => 'https://images.unsplash.com/photo-1572177812156-58036aae439c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Tailoring workshop'],
            ['src' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'IT training'],
            ['src' => 'https://images.unsplash.com/photo-1573164713988-8665fc963095?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Graduation day'],
        ],
        'sidebar_facts' => [
            ['label' => 'Started', 'value' => '2020'],
            ['label' => 'Scholarship students', 'value' => '200 active'],
            ['label' => 'Vocational graduates', 'value' => '680'],
            ['label' => 'Employment rate', 'value' => '87% within 6 months'],
            ['label' => 'Trades offered', 'value' => '6'],
            ['label' => 'Corporate partners', 'value' => '14'],
        ],
        'support_text' => '₦75,000 sponsors one vocational student for a full 6-month program. ₦150,000 sends a child to secondary school for a year. Will you invest in a young person\'s future?',
    ],

    'healing-hands' => [
        'slug' => 'healing-hands',
        'name' => 'Healing Hands',
        'tag' => 'Medical Care',
        'meta_description' => 'Healing Hands — CHJ Foundation\'s medical care program. Free clinics, maternal care, and emergency medical assistance in Abuja.',
        'hero_intro' => 'Two permanent clinics. Monthly mobile clinics to rural communities. A maternal care program serving 180 women a year. Healthcare for those without.',
        'hero_image' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'quick_stats' => [
            ['value' => '4.2K', 'label' => 'Consultations in 2024'],
            ['value' => '180', 'label' => 'Mothers served annually'],
            ['value' => '2', 'label' => 'Permanent clinics'],
        ],
        'about_title' => 'Healthcare should not be a luxury. In our communities, it often is.',
        'about_paragraphs' => [
            'For the families we serve, a simple illness can become catastrophic. A child with malaria may die because the family cannot afford ₦2,000 for treatment. A pregnant woman may go into labor without ever seeing a midwife. A diabetic grandfather may ration his insulin because his pension does not stretch that far.',
            'Healing Hands began in 2020 as a monthly volunteer clinic in our Jabi community hall. Dr. Ngozi Eze, our medical lead, brought three colleagues and they saw 60 patients that first day. Today, we run two permanent clinics — in Jabi and Nyanya — open five days a week, plus monthly mobile clinics that travel to rural communities in Niger and Nasarawa states.',
            'Our clinics offer primary care, maternal and child health, vaccinations, chronic disease management, and basic laboratory testing. We employ two full-time nurses and rotate a network of 24 volunteer doctors, pharmacists, and lab technicians. All services are free for registered patients.',
            'For cases beyond our capacity, we run an Emergency Medical Fund — providing life-saving treatment at partner hospitals for those who cannot afford it. In 2024, the fund covered 47 surgeries, 12 cancer treatments, and 8 emergency obstetric interventions.',
        ],
        'approach_points' => [
            ['title' => 'Two permanent clinics', 'desc' => 'Jabi (Mon–Fri) and Nyanya (Tue–Sat). Free primary care, vaccinations, and chronic disease management for registered patients.'],
            ['title' => 'Monthly mobile clinics', 'desc' => 'A team of volunteer doctors, nurses, and pharmacists travels to 4 rural communities each month, seeing 80–120 patients per visit.'],
            ['title' => 'Maternal care program', 'desc' => 'Full antenatal, delivery, and postnatal care for 180 women annually, in partnership with two government hospitals.'],
            ['title' => 'Emergency medical fund', 'desc' => 'Covers life-saving treatment (surgeries, cancer care, obstetric emergencies) at partner hospitals for those who cannot afford it.'],
            ['title' => 'Health education', 'desc' => 'Monthly workshops in community halls on hygiene, nutrition, family planning, and common disease prevention.'],
        ],
        'quote' => [
            'text' => 'When my daughter was born prematurely, I had no money for the incubator. Healing Hands paid for it. Today she is a healthy two-year-old. I have no words for what they did for us.',
            'author' => 'Funmi, mother, Nyanya',
        ],
        'gallery' => [
            ['src' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Doctor examining patient'],
            ['src' => 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Mobile clinic'],
            ['src' => 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Maternal care'],
            ['src' => 'https://images.unsplash.com/photo-1583912267550-d44c9c1cd9b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Pharmacy'],
        ],
        'sidebar_facts' => [
            ['label' => 'Started', 'value' => '2020'],
            ['label' => 'Clinics', 'value' => '2 permanent + 4 mobile'],
            ['label' => 'Consultations (2024)', 'value' => '4,200'],
            ['label' => 'Volunteer doctors', 'value' => '24'],
            ['label' => 'Maternal patients', 'value' => '180 / year'],
            ['label' => 'Emergency fund cases', 'value' => '67 in 2024'],
        ],
        'support_text' => '₦50,000 funds one mobile clinic day reaching 100 patients. ₦250,000 covers a full antenatal-to-delivery package for one mother. Help us heal.',
    ],

    'bright-futures' => [
        'slug' => 'bright-futures',
        'name' => 'Bright Futures',
        'tag' => 'Youth Mentorship',
        'meta_description' => 'Bright Futures — CHJ Foundation\'s youth mentorship program. One-to-one mentorship, life skills, and faith formation for young people in Abuja.',
        'hero_intro' => 'One-to-one mentorship, life skills, and faith formation for young people aged 10–18. Building the next generation of compassionate leaders.',
        'hero_image' => 'https://images.unsplash.com/photo-1509062522246-3755977927d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'quick_stats' => [
            ['value' => '1,150', 'label' => 'Youth mentored'],
            ['value' => '180', 'label' => 'Active mentors'],
            ['value' => '95%', 'label' => 'Complete the program'],
        ],
        'about_title' => 'Every young person deserves someone who believes in them.',
        'about_paragraphs' => [
            'In the neighborhoods where we work, too many young people grow up without steady adults in their corner. Fathers are absent. Mothers are working three jobs. Teachers are overwhelmed. The streets are full of alternatives — and not the good kind.',
            'Bright Futures matches young people aged 10–18 with trained adult mentors who commit to a minimum of one year of weekly meetings. The mentor shows up. Listens. Helps with homework. Takes them to a football match. Talks about life. Prays with them if they want. Becomes a steady presence in a world that has been anything but steady.',
            'Beyond one-to-one mentoring, we run weekly group sessions on life skills (communication, conflict resolution, financial literacy, sexual health), holiday camps three times a year, and faith formation in partnership with local churches of various denominations.',
            'We measure success not just in school grades (though those improve significantly) but in character. Are our mentees kind? Do they help others? Do they make wise choices? Are they growing into the people they were created to be? These are the questions that matter to us.',
        ],
        'approach_points' => [
            ['title' => 'One-to-one mentor matching', 'desc' => 'Carefully screened and trained adult mentors, matched with youth based on personality, interests, and needs. Minimum one-year commitment.'],
            ['title' => 'Weekly group sessions', 'desc' => 'Life skills, character formation, and faith conversations in small groups of 8–12 youth, led by trained facilitators.'],
            ['title' => 'Holiday camps', 'desc' => 'Three residential camps per year — a week each at Easter, August, and December. Sports, arts, faith, friendship, and a break from tough neighborhoods.'],
            ['title' => 'Family engagement', 'desc' => 'Quarterly gatherings with parents/guardians, plus home visits. We work with the whole family system, not just the youth.'],
            ['title' => 'Faith formation', 'desc' => 'Optional, ecumenical Christian formation in partnership with local churches. We respect each young person\'s tradition and family choices.'],
        ],
        'quote' => [
            'text' => 'I was angry at the world when I started with Bright Futures. My mentor, Mr. David, didn\'t try to fix me. He just kept showing up. After a year I realized I was less angry. After two years I wanted to be a mentor myself. Now I am.',
            'author' => 'Samuel, age 19, former mentee, now junior mentor',
        ],
        'gallery' => [
            ['src' => 'https://images.unsplash.com/photo-1509062522246-3755977927d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Mentor and mentee'],
            ['src' => 'https://images.unsplash.com/photo-1530541930197-ff16ac917b0e?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Group session'],
            ['src' => 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Holiday camp'],
            ['src' => 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80', 'alt' => 'Youth activity'],
        ],
        'sidebar_facts' => [
            ['label' => 'Started', 'value' => '2021'],
            ['label' => 'Active youth', 'value' => '240'],
            ['label' => 'Active mentors', 'value' => '180'],
            ['label' => 'Completion rate', 'value' => '95%'],
            ['label' => 'Average match length', 'value' => '2.3 years'],
            ['label' => 'Holiday camps / year', 'value' => '3'],
        ],
        'support_text' => 'Become a mentor — we are always looking for committed adults. Or sponsor a young person\'s participation for ₦60,000 per year (includes camps, materials, and facilitator support).',
    ],

];
